"""empty message

Revision ID: 17a6ed9e6618
Revises: 95e0c5ece9e4
Create Date: 2024-06-22 03:38:19.890866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17a6ed9e6618'
down_revision = '95e0c5ece9e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('github_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('token_type', sa.String(length=40), nullable=False),
    sa.Column('access_token', sa.String(length=200), nullable=False),
    sa.Column('refresh_token', sa.String(length=40), nullable=False),
    sa.Column('expires_at', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['author.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('github_token')
    # ### end Alembic commands ###
