"""empty message

Revision ID: 1e0be1d0a225
Revises: bfcb038ef776
Create Date: 2024-06-22 06:23:22.038175

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1e0be1d0a225'
down_revision = 'bfcb038ef776'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('branch', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=False))
        batch_op.drop_column('path')
        batch_op.drop_column('title')
        batch_op.drop_column('ssh')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ssh', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('title', mysql.VARCHAR(length=64), nullable=False))
        batch_op.add_column(sa.Column('path', mysql.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('owner_id')
        batch_op.drop_column('branch')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
