"""empty message

Revision ID: bfcb038ef776
Revises: 4f89e33927e9
Create Date: 2024-06-22 04:08:06.987282

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bfcb038ef776'
down_revision = '4f89e33927e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('github_token', schema=None) as batch_op:
        batch_op.alter_column('refresh_token',
               existing_type=mysql.VARCHAR(length=40),
               nullable=True)
        batch_op.alter_column('expires_at',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('github_token', schema=None) as batch_op:
        batch_op.alter_column('expires_at',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('refresh_token',
               existing_type=mysql.VARCHAR(length=40),
               nullable=False)

    # ### end Alembic commands ###
